/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pratikum170625;

/**
 *
 * @author FA506NF
 */
public class menumakanan extends javax.swing.JFrame {

    private menuutama utama;
    
    public menumakanan() {
        initComponents();
    }
    public menumakanan(menuutama utama){
        this.utama = utama;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        chk_nasgor = new javax.swing.JCheckBox();
        chk_soto = new javax.swing.JCheckBox();
        chk_ageprek = new javax.swing.JCheckBox();
        chk_bakso = new javax.swing.JCheckBox();
        txtnasgor = new javax.swing.JTextField();
        txtsoto = new javax.swing.JTextField();
        txtgeprek = new javax.swing.JTextField();
        txtbakso = new javax.swing.JTextField();
        cbnasgor = new javax.swing.JComboBox<>();
        cbsoto = new javax.swing.JComboBox<>();
        cbgeprek = new javax.swing.JComboBox<>();
        cbbakso = new javax.swing.JComboBox<>();
        txt_nasgor = new javax.swing.JTextField();
        txt_soto = new javax.swing.JTextField();
        txt_geprek = new javax.swing.JTextField();
        txt_bakso = new javax.swing.JTextField();
        btntotal = new javax.swing.JButton();
        txttotal = new javax.swing.JTextField();
        btnkembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("MENU MAKANAN");

        chk_nasgor.setText("Nasi Goreng");
        chk_nasgor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_nasgorActionPerformed(evt);
            }
        });

        chk_soto.setText("Soto");
        chk_soto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_sotoActionPerformed(evt);
            }
        });

        chk_ageprek.setText("Ayam Geprek");
        chk_ageprek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_ageprekActionPerformed(evt);
            }
        });

        chk_bakso.setText("Bakso");
        chk_bakso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_baksoActionPerformed(evt);
            }
        });

        txtnasgor.setText("0");

        txtsoto.setText("0");
        txtsoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsotoActionPerformed(evt);
            }
        });

        txtgeprek.setText("0");
        txtgeprek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgeprekActionPerformed(evt);
            }
        });

        txtbakso.setText("0");

        cbnasgor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbnasgor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbnasgorActionPerformed(evt);
            }
        });

        cbsoto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbsoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbsotoActionPerformed(evt);
            }
        });

        cbgeprek.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbgeprek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbgeprekActionPerformed(evt);
            }
        });

        cbbakso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbbakso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbaksoActionPerformed(evt);
            }
        });

        txt_nasgor.setText("0");
        txt_nasgor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nasgorActionPerformed(evt);
            }
        });

        txt_soto.setText("0");

        txt_geprek.setText("0");

        txt_bakso.setText("0");

        btntotal.setText("Total");
        btntotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntotalActionPerformed(evt);
            }
        });

        txttotal.setText("0");

        btnkembali.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnkembali.setText("Kembali ke Menu Utama");
        btnkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(365, 365, 365))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnkembali, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(130, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(chk_ageprek)
                                            .addComponent(chk_soto, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(chk_bakso, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtbakso, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtgeprek)
                                            .addComponent(txtsoto)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(chk_nasgor)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtnasgor, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(81, 81, 81)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cbgeprek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbbakso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbsoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbnasgor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btntotal, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_geprek)
                                    .addComponent(txt_bakso, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_soto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_nasgor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txttotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btntotal))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtnasgor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbnasgor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_nasgor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chk_nasgor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chk_soto)
                            .addComponent(txtsoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbsoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_soto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chk_ageprek)
                            .addComponent(txtgeprek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbgeprek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_geprek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtbakso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbakso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_bakso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chk_bakso, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(btnkembali, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(914, 442));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void chk_nasgorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_nasgorActionPerformed
        txtnasgor.setText("15000");
    }//GEN-LAST:event_chk_nasgorActionPerformed

    private void txtsotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsotoActionPerformed

    private void cbnasgorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbnasgorActionPerformed
        int jml = (int)cbnasgor.getSelectedIndex();
        double harga = Double.parseDouble(txtnasgor.getText());
        double total = jml*harga;
        txt_nasgor.setText(Double.toString(total));
    }//GEN-LAST:event_cbnasgorActionPerformed

    private void txt_nasgorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nasgorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nasgorActionPerformed

    private void txtgeprekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgeprekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgeprekActionPerformed

    private void btntotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntotalActionPerformed
        double hnasgor = Double.parseDouble(txt_nasgor.getText());
        double hsoto = Double.parseDouble(txt_soto.getText());
        double hgeprek = Double.parseDouble(txt_geprek.getText());
        double hbakso = Double.parseDouble(txt_bakso.getText());
        double htotal = hnasgor + hsoto + hgeprek + hbakso;
        
        txttotal.setText(Double.toString(htotal));
        
        
    }//GEN-LAST:event_btntotalActionPerformed

    private void chk_sotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_sotoActionPerformed
        txtsoto.setText("15000");
    }//GEN-LAST:event_chk_sotoActionPerformed

    private void chk_ageprekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_ageprekActionPerformed
        txtgeprek.setText("12000");
    }//GEN-LAST:event_chk_ageprekActionPerformed

    private void chk_baksoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_baksoActionPerformed
        txtbakso.setText("12000");
    }//GEN-LAST:event_chk_baksoActionPerformed

    private void cbsotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbsotoActionPerformed
        int jml = (int)cbsoto.getSelectedIndex();
        double harga = Double.parseDouble(txtsoto.getText());
        double total = jml*harga;
        txt_soto.setText(Double.toString(total));
    }//GEN-LAST:event_cbsotoActionPerformed

    private void cbgeprekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbgeprekActionPerformed
        int jml = (int)cbgeprek.getSelectedIndex();
        double harga = Double.parseDouble(txtgeprek.getText());
        double total = jml*harga;
        txt_geprek.setText(Double.toString(total));
    }//GEN-LAST:event_cbgeprekActionPerformed

    private void cbbaksoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbaksoActionPerformed
        int jml = (int)cbbakso.getSelectedIndex();
        double harga = Double.parseDouble(txtbakso.getText());
        double total = jml*harga;
        txt_bakso.setText(Double.toString(total));
    }//GEN-LAST:event_cbbaksoActionPerformed

    private void btnkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkembaliActionPerformed
        String total = txttotal.getText();
        utama.setTotalMakanan(total);
        this.dispose(); //menutup jendela form menu makanan
    }//GEN-LAST:event_btnkembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menumakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menumakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menumakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menumakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new menumakanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnkembali;
    private javax.swing.JButton btntotal;
    private javax.swing.JComboBox<String> cbbakso;
    private javax.swing.JComboBox<String> cbgeprek;
    private javax.swing.JComboBox<String> cbnasgor;
    private javax.swing.JComboBox<String> cbsoto;
    private javax.swing.JCheckBox chk_ageprek;
    private javax.swing.JCheckBox chk_bakso;
    private javax.swing.JCheckBox chk_nasgor;
    private javax.swing.JCheckBox chk_soto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txt_bakso;
    private javax.swing.JTextField txt_geprek;
    private javax.swing.JTextField txt_nasgor;
    private javax.swing.JTextField txt_soto;
    private javax.swing.JTextField txtbakso;
    private javax.swing.JTextField txtgeprek;
    private javax.swing.JTextField txtnasgor;
    private javax.swing.JTextField txtsoto;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
