/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pratikum170625;

/**
 *
 * @author FA506NF
 */
public class menuminuman extends javax.swing.JFrame {

    private menuutama utama;
    
    public menuminuman() {
        initComponents();
    }
    public menuminuman(menuutama utama){
        this.utama = utama;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        chkamericano = new javax.swing.JCheckBox();
        chklatte = new javax.swing.JCheckBox();
        chklemon = new javax.swing.JCheckBox();
        chkkopsu = new javax.swing.JCheckBox();
        chkmandi = new javax.swing.JCheckBox();
        chkes = new javax.swing.JCheckBox();
        txtamericano = new javax.swing.JTextField();
        txtlatte = new javax.swing.JTextField();
        txtlemon = new javax.swing.JTextField();
        txtkopsu = new javax.swing.JTextField();
        txtmandi = new javax.swing.JTextField();
        txtes = new javax.swing.JTextField();
        cb_americano = new javax.swing.JComboBox<>();
        cb_latte = new javax.swing.JComboBox<>();
        cb_lemon = new javax.swing.JComboBox<>();
        cb_kopsu = new javax.swing.JComboBox<>();
        cb_mandi = new javax.swing.JComboBox<>();
        cb_es = new javax.swing.JComboBox<>();
        txt_americano = new javax.swing.JTextField();
        txt_latte = new javax.swing.JTextField();
        txt_lemon = new javax.swing.JTextField();
        txt_kopsu = new javax.swing.JTextField();
        txt_mandi = new javax.swing.JTextField();
        txt_es = new javax.swing.JTextField();
        btntotal = new javax.swing.JButton();
        txttotal = new javax.swing.JTextField();
        btnkembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("MENU MINUMAN");

        chkamericano.setText("Americano");
        chkamericano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkamericanoActionPerformed(evt);
            }
        });

        chklatte.setText("Coffe Latte");
        chklatte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chklatteActionPerformed(evt);
            }
        });

        chklemon.setText("Lemon Tea");
        chklemon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chklemonActionPerformed(evt);
            }
        });

        chkkopsu.setText("Kopi Susu");
        chkkopsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkkopsuActionPerformed(evt);
            }
        });

        chkmandi.setText("Manis Dingin");
        chkmandi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkmandiActionPerformed(evt);
            }
        });

        chkes.setText("Es Kosong");
        chkes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkesActionPerformed(evt);
            }
        });

        txtamericano.setText("0");

        txtlatte.setText("0");

        txtlemon.setText("0");
        txtlemon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlemonActionPerformed(evt);
            }
        });

        txtkopsu.setText("0");
        txtkopsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkopsuActionPerformed(evt);
            }
        });

        txtmandi.setText("0");

        txtes.setText("0");

        cb_americano.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cb_americano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_americanoActionPerformed(evt);
            }
        });

        cb_latte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cb_latte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_latteActionPerformed(evt);
            }
        });

        cb_lemon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cb_lemon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_lemonActionPerformed(evt);
            }
        });

        cb_kopsu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cb_kopsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_kopsuActionPerformed(evt);
            }
        });

        cb_mandi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cb_mandi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_mandiActionPerformed(evt);
            }
        });

        cb_es.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cb_es.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_esActionPerformed(evt);
            }
        });

        txt_americano.setText("0");

        txt_latte.setText("0");

        txt_lemon.setText("0");

        txt_kopsu.setText("0");

        txt_mandi.setText("0");

        txt_es.setText("0");

        btntotal.setText("Total");
        btntotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntotalActionPerformed(evt);
            }
        });

        txttotal.setText("0");

        btnkembali.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnkembali.setText("Kembali ke Menu Utama");
        btnkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(chklatte)
                                .addComponent(chkamericano)
                                .addComponent(chklemon)
                                .addComponent(chkkopsu, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(chkmandi)
                            .addComponent(chkes))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtamericano)
                            .addComponent(txtlatte)
                            .addComponent(txtlemon)
                            .addComponent(txtkopsu)
                            .addComponent(txtmandi)
                            .addComponent(txtes, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cb_kopsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69)
                                .addComponent(txt_kopsu, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cb_mandi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69)
                                .addComponent(txt_mandi, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cb_lemon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cb_latte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cb_americano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(69, 69, 69)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_lemon, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                    .addComponent(txt_latte)
                                    .addComponent(txt_americano)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cb_es, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69)
                                .addComponent(txt_es, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(315, 315, 315)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnkembali, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btntotal, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkamericano)
                    .addComponent(txtamericano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_americano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_americano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chklatte)
                    .addComponent(txtlatte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_latte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_latte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chklemon)
                    .addComponent(txtlemon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_lemon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_lemon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkkopsu)
                    .addComponent(txtkopsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_kopsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_kopsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkmandi)
                    .addComponent(txtmandi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_mandi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_mandi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkes)
                    .addComponent(txtes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_es, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_es, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btntotal)
                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnkembali, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(747, 483));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void chkamericanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkamericanoActionPerformed
        txtamericano.setText("15000");
    }//GEN-LAST:event_chkamericanoActionPerformed

    private void chkmandiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkmandiActionPerformed
        txtmandi.setText("5000");
    }//GEN-LAST:event_chkmandiActionPerformed

    private void txtlemonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlemonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlemonActionPerformed

    private void txtkopsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkopsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkopsuActionPerformed

    private void btntotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntotalActionPerformed
        double americano = Double.parseDouble(txt_americano.getText());
        double latte = Double.parseDouble(txt_latte.getText());
        double lemon = Double.parseDouble(txt_lemon.getText());
        double kopsu = Double.parseDouble(txt_kopsu.getText());
        double mandi = Double.parseDouble(txt_mandi.getText());
        double es = Double.parseDouble(txt_es.getText());
        
        double htotal = americano + latte + lemon + kopsu + mandi + es;
        
        txttotal.setText(Double.toString(htotal));
    }//GEN-LAST:event_btntotalActionPerformed

    private void chklatteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chklatteActionPerformed
        txtlatte.setText("17000");
    }//GEN-LAST:event_chklatteActionPerformed

    private void chklemonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chklemonActionPerformed
        txtlemon.setText("13000");
    }//GEN-LAST:event_chklemonActionPerformed

    private void chkkopsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkkopsuActionPerformed
        txtkopsu.setText("10000");
    }//GEN-LAST:event_chkkopsuActionPerformed

    private void chkesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkesActionPerformed
        txtes.setText("2000");
    }//GEN-LAST:event_chkesActionPerformed

    private void cb_americanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_americanoActionPerformed
        int jml = (int)cb_americano.getSelectedIndex();
        double harga = Double.parseDouble(txtamericano.getText());
        double total = jml*harga;
        txt_americano.setText(Double.toString(total));
    }//GEN-LAST:event_cb_americanoActionPerformed

    private void cb_latteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_latteActionPerformed
        int jml = (int)cb_latte.getSelectedIndex();
        double harga = Double.parseDouble(txtlatte.getText());
        double total = jml*harga;
        txt_latte.setText(Double.toString(total));
    }//GEN-LAST:event_cb_latteActionPerformed

    private void cb_lemonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_lemonActionPerformed
        int jml = (int)cb_lemon.getSelectedIndex();
        double harga = Double.parseDouble(txtlemon.getText());
        double total = jml*harga;
        txt_lemon.setText(Double.toString(total));
    }//GEN-LAST:event_cb_lemonActionPerformed

    private void cb_kopsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_kopsuActionPerformed
        int jml = (int)cb_kopsu.getSelectedIndex();
        double harga = Double.parseDouble(txtkopsu.getText());
        double total = jml*harga;
        txt_kopsu.setText(Double.toString(total));
    }//GEN-LAST:event_cb_kopsuActionPerformed

    private void cb_mandiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_mandiActionPerformed
        int jml = (int)cb_mandi.getSelectedIndex();
        double harga = Double.parseDouble(txtmandi.getText());
        double total = jml*harga;
        txt_mandi.setText(Double.toString(total));
    }//GEN-LAST:event_cb_mandiActionPerformed

    private void cb_esActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_esActionPerformed
        int jml = (int)cb_es.getSelectedIndex();
        double harga = Double.parseDouble(txtes.getText());
        double total = jml*harga;
        txt_es.setText(Double.toString(total));
    }//GEN-LAST:event_cb_esActionPerformed

    private void btnkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkembaliActionPerformed
        String total = txttotal.getText();
        utama.setTotalMinuman(total);
        this.dispose(); //menutup jendela form menu makanan
    }//GEN-LAST:event_btnkembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuminuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuminuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuminuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuminuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuminuman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnkembali;
    private javax.swing.JButton btntotal;
    private javax.swing.JComboBox<String> cb_americano;
    private javax.swing.JComboBox<String> cb_es;
    private javax.swing.JComboBox<String> cb_kopsu;
    private javax.swing.JComboBox<String> cb_latte;
    private javax.swing.JComboBox<String> cb_lemon;
    private javax.swing.JComboBox<String> cb_mandi;
    private javax.swing.JCheckBox chkamericano;
    private javax.swing.JCheckBox chkes;
    private javax.swing.JCheckBox chkkopsu;
    private javax.swing.JCheckBox chklatte;
    private javax.swing.JCheckBox chklemon;
    private javax.swing.JCheckBox chkmandi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txt_americano;
    private javax.swing.JTextField txt_es;
    private javax.swing.JTextField txt_kopsu;
    private javax.swing.JTextField txt_latte;
    private javax.swing.JTextField txt_lemon;
    private javax.swing.JTextField txt_mandi;
    private javax.swing.JTextField txtamericano;
    private javax.swing.JTextField txtes;
    private javax.swing.JTextField txtkopsu;
    private javax.swing.JTextField txtlatte;
    private javax.swing.JTextField txtlemon;
    private javax.swing.JTextField txtmandi;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
